### ISSUE TITLE
some convert is  not smart ,is there any configure to set?

### ISSUE THREAD

**Issue by l2009312042** [as-ideas/DeepPhonemizer#10]
use  en_us_cmudict_forward.pt model ,
DON'T    [D][IY]-[OW]-[EH][N]-[T][IY
YOU'LL   [W][AY]-[OW]-[Y][UW]-[EH][L]-[EH][L]
BERGSON  [B][IY]-[IY]-[AA][R]-[JH][IY]-[EH][S]-[OW]-[EH][N]

**Comment by cschaefer26** [comment]
Hi, uppercase words are treated as acronyms by default, try:

`phonemizer("DON'T", lang='en_us', expand_acronyms=False)`

**Comment by l2009312042** [comment]
thanks ，  that is work ！
