### ISSUE TITLE
Problem exporting with JIT

### ISSUE THREAD

**Issue by iggygeek** [as-ideas/DeepPhonemizer#11]
Hello,
I had a problem when running the export code snippet in the Readme :
>> RuntimeError: 
>> Unknown type name 'torch.tensor':

Any ideas ?
Thanks

**Comment by cschaefer26** [comment]
Hi, yes this is an old type hint error, that is fixed in the current version. Try to update the latest lib version (0.016).

**Comment by iggygeek** [comment]
Thx, it worked!
