### ISSUE TITLE
[BUG] On Windows 10 "preprocessor.phoneme_tokenizer" not output token id which is greater than 28

### ISSUE THREAD

**Issue by ttklm20** [as-ideas/DeepPhonemizer#12]
I found a bug on Windows 10.  "preprocessor.phoneme_tokenizer" function doesn't work properly as it will not output token id whch is greater than 28. The problem is caused by the encoding settings while reading the configuration file.

For fixing the bug, please and " encoding='utf-8' " in line 21 in "dp/utils/io.py".

```python

    with open(path, 'r', encoding="utf-8") as stream:
        config = yaml.load(stream, Loader=yaml.FullLoader)
    return config

```

**Comment by cschaefer26** [comment]
Hi thanks for the remark, fixed with 0.0.17!
