### ISSUE TITLE
`dp.utils` logging config is overriding app logging

### ISSUE THREAD

**Issue by moritzhaller** [as-ideas/DeepPhonemizer#25]
https://github.com/as-ideas/DeepPhonemizer/blob/main/dp/utils/logging.py#L13 is overriding app-level logging config at runtime when importing `DeepPhonemizer`. According to https://stackoverflow.com/a/27017068 and https://docs.python.org/3/howto/logging.html#library-config it might make sense to remove the logging config.

**Comment by cschaefer26** [comment]
Hi, thanks for the PR. Could it make sense to move the logging config into the entry points of the repo for training? E.g. in run_training.py to not lose the formatting.

**Comment by moritzhaller** [comment]
@cschaefer26 yes I think that makes sense 👍

**Comment by moritzhaller** [comment]
@cschaefer26 I have created an example PR https://github.com/as-ideas/DeepPhonemizer/pull/30

`run_training.py` and `run_prediction.py` are both users of the `dp` package, with potentially different logging needs.

E.g. `run_prediction.py` might set have the `DEBUG` log level defined in development:
```
$ python run_prediction.py
2023-02-24 06:41:00,775.775 DEBUG phonemizer:  Initializing phonemizer with model step 710000
['jʌŋ']
```

and to `INFO` in production:

```
$ python run_prediction.py
['jʌŋ']
```

**Comment by cschaefer26** [comment]
Thank you! I will have a look.

**Comment by moritzhaller** [comment]
just realised there is a conflict, will resolve if you agree with the approach. Could also find a nicer place for `logging.yaml` potentially ;)

**Comment by cschaefer26** [comment]
Yeah, I'll merge/review.
