### ISSUE TITLE
checkpoint: en_us_cmudict_forward

### ISSUE THREAD

**Issue by staehlmich** [as-ideas/DeepPhonemizer#8]
Hello, love your resource and would like to use it to convert phrases to Arpabet symbols. I noticed that the link to the checkpoint "en_us_cmudict_forward" is the same as "en_us_cmudict_ipa_forward". Could you please link the correct file? Thank you!

**Comment by cschaefer26** [comment]
Hello, thanks for pointing that out, I corrected the link. The output should look like this:

`   checkpoint_path = '/Users/cschaefe/Downloads/en_us_cmudict_forward.pt'
    phonemizer = Phonemizer.from_checkpoint(checkpoint_path)

    text = 'young'
    result = phonemizer('staehlmich', lang='en_us')
    print(result)`

[S][T][AA][L][M][IH][CH]
